import {Referee} from '../referee/referee.js';
import {resolveDuel} from './duelSystem.js';
import {launchBall} from '../physics/ballPhysics.js';
const POSSESSION={HOME:'home',AWAY:'away',NONE:'none',CONTESTED:'contested'};
const ACTIONS={PASS:'pass',CARRY:'carry',DRIBBLE:'dribble',SHOOT:'shoot',CROSS:'cross',CLEAR:'clear',HOLD:'hold',PRESS:'press',TACKLE:'tackle',MOVE:'move',SUPPORT:'support',NONE:'none'};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):a));
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const rng01=r=>clamp(typeof r==='function'?r():r?.next?.()??r?.random?.()??Math.random());
const pos=p=>p?.position??{x:p?.x??.5,y:p?.y??.5};
const dist=(a,b)=>Math.hypot(pos(a).x-pos(b).x,pos(a).y-pos(b).y);
const sideOf=(state,p)=>p?.side??p?.team??(['home','away'].find(s=>(state?.teams?.[s]?.players??[]).some(x=>String(x.id)===String(p?.id)))??null);
const players=(state,side)=>((state?.teams?.[side]?.players??[])).filter(p=>p&&p.onPitch!==false&&!p.substituted&&!p.redCard&&!p.injured);
const all=(state)=>[...players(state,'home'),...players(state,'away')];
const byId=(state,id)=>all(state).find(p=>String(p.id)===String(id))??null;
const attr=(p,k,d=50)=>num(p?.attributes?.technical?.[k]??p?.attributes?.mental?.[k]??p?.attributes?.physical?.[k]??p?.[k],d);
const emit=(fn,type,payload={},causedBy=null)=>fn?.({type,payload,causedBy});
function clearFlags(state){for(const p of all(state)){p.hasBall=false;p.matchState??={};p.matchState.hasBall=false;}}
export function setPossession(state,side,playerId,{silent=false,emitEvent=null,reason='recovery'}={}){const p=byId(state,playerId),s=side==='home'||side==='away'?side:sideOf(state,p);if(!p||!s||p.onPitch===false)return false;clearFlags(state);p.hasBall=true;p.matchState??={};p.matchState.hasBall=true;state.ball??={};state.ball.ownerId=p.id;state.ball.ownerSide=s;state.ball.state='controlled';state.ball.lastTouchPlayerId=p.id;state.ball.lastTouchSide=s;state.ball.x=pos(p).x;state.ball.y=pos(p).y;state.ball.position={x:pos(p).x,y:pos(p).y};state.possession=s;state.possessionSide=s;state.possessionPlayerId=p.id;state._lastPossessionChangeTime=num(state.clock?.totalSeconds,state.timeSeconds);if(!silent)emit(emitEvent,'POSSESSION_WON',{side:s,playerId:p.id,reason},p.id);return true;}
function loose(state){clearFlags(state);state.ball??={};state.ball.ownerId=null;state.ball.ownerSide=POSSESSION.NONE;state.ball.state='contested';state.possession=POSSESSION.CONTESTED;state.possessionPlayerId=null;}
function targetPass(state,p,decision,r){const s=sideOf(state,p),list=players(state,s).filter(x=>String(x.id)!==String(p.id));const id=decision?.targetPlayerId??decision?.receiverId??decision?.targetId;if(id){const x=list.find(q=>String(q.id)===String(id));if(x)return x;}return list.sort((a,b)=>dist(p,a)-dist(p,b))[Math.floor(rng01(r)*Math.min(3,list.length))]??list[0]??null;}
function passProb(state,p,t){const d=dist(p,t),space=clamp(1-Math.min(...players(state,sideOf(state,t)==='home'?'away':'home').map(o=>dist(t,o)))/.25);return clamp(.42+attr(p,'passaggi')/99*.22+attr(p,'visione')/99*.16+attr(t,'primoControllo')/99*.08+space*.10-d*.12);
}
function performPass(state,p,d,r,emitEvent){const t=targetPass(state,p,d,r);if(!t)return{executed:false,result:'no_target'};const probability=passProb(state,p,t),roll=rng01(r);emit(emitEvent,'PASS',{playerId:p.id,passerId:p.id,receiverId:t.id,from:pos(p),to:pos(t),probability,roll,completed:roll<=probability},p.id);p.matchStats??={};p.matchStats.passesAttempted=(p.matchStats.passesAttempted??0)+1;if(roll<=probability){p.matchStats.passesCompleted=(p.matchStats.passesCompleted??0)+1;setPossession(state,sideOf(state,t),t.id,{silent:true});emit(emitEvent,'PASS_COMPLETED',{passerId:p.id,receiverId:t.id,probability},p.id);return{executed:true,result:'completed',receiver:t,probability};}const opp=players(state,sideOf(state,p)==='home'?'away':'home').sort((a,b)=>dist(t,a)-dist(t,b))[0];if(opp&&dist(t,opp)<.085){setPossession(state,sideOf(state,opp),opp.id,{silent:true});emit(emitEvent,'PASS_INTERCEPTED',{passerId:p.id,receiverId:t.id,interceptorId:opp.id,probability,roll},opp.id);return{executed:true,result:'intercepted',receiver:opp,probability};}launchBall({ball:state.ball,from:pos(p),to:pos(t),speed:.20,state:'loose'});loose(state);return{executed:true,result:'failed',probability};}
function performDribble(state,p,r,emitEvent){const s=sideOf(state,p),opp=players(state,s==='home'?'away':'home').sort((a,b)=>dist(p,a)-dist(p,b))[0];if(opp&&dist(p,opp)<.085){const d=resolveDuel({state,attacker:p,defender:opp,rngSource:r,emitEvent});if(d?.foul?.type==='FOUL'&&!d.advantage?.played)return{executed:true,result:'foul',duel:d};if(d?.winner==='defender'){setPossession(state,s==='home'?'away':'home',opp.id,{silent:true,reason:'duel_win'});return{executed:true,result:'tackled',duel:d};}}
const prob=clamp(.35+attr(p,'dribbling')/99*.38+attr(p,'agilita')/99*.10-rng01(r)*.08);if(rng01(r)<=prob){p.position={x:clamp(p.position.x+(s==='home'?.025:-.025),.025,.975),y:p.position.y};return{executed:true,result:'beaten',probability:prob};}loose(state);return{executed:true,result:'lost',probability:prob};}
function performShoot(state,p,r,emitEvent){const s=sideOf(state,p),goalX=s==='home'?.975:.025,dx=goalX-p.position.x,proximity=clamp(1-dist(p,{position:{x:goalX,y:p.position.y}})/.75),prob=clamp(.015+attr(p,'finalizzazione')/99*.055+attr(p,'tiro')/99*.035+proximity*.045);const roll=rng01(r);p.matchStats??={};p.matchStats.shots=(p.matchStats.shots??0)+1;emit(emitEvent,'SHOT',{playerId:p.id,side:s,probability:prob,roll,position:pos(p)},p.id);if(roll<prob){state.score??={home:0,away:0};state.score[s]=(state.score[s]??0)+1;p.matchStats.goals=(p.matchStats.goals??0)+1;state.ball.lastTouchPlayerId=p.id;state.ball.ownerId=null;state.ball.state='goal';state.lastGoalPlayerId=p.id;emit(emitEvent,'GOAL',{scoringSide:s,playerId:p.id,score:{...state.score}},p.id);const restartSide=s==='home'?'away':'home';const restart=players(state,restartSide).sort((a,b)=>Math.abs(a.position.x-.5)-Math.abs(b.position.x-.5))[0];if(restart)setPossession(state,restartSide,restart.id,{silent:true,reason:'kickoff_after_goal'});return{executed:true,result:'goal',probability:prob};}const keeper=players(state,s==='home'?'away':'home').find(x=>x.isGoalkeeper||String(x.role??x.primaryRole??'').toLowerCase().includes('portiere'));if(roll<prob+.28&&keeper){keeper.matchStats??={};keeper.matchStats.saves=(keeper.matchStats.saves??0)+1;setPossession(state,s==='home'?'away':'home',keeper.id,{silent:true,reason:'save'});emit(emitEvent,'SAVE',{shooterId:p.id,keeperId:keeper.id},keeper.id);return{executed:true,result:'saved',probability:prob};}emit(emitEvent,'SHOT_MISSED',{playerId:p.id,side:s},p.id);return{executed:true,result:'missed',probability:prob};}
function execute(state,p,decision,r,emitEvent){const a=String(decision?.action??decision?.intent??'hold').toLowerCase();if(a==='pass'||a==='cross')return performPass(state,p,decision,r,emitEvent);if(a==='dribble'||a==='carry')return performDribble(state,p,r,emitEvent);if(a==='shoot')return performShoot(state,p,r,emitEvent);if(a==='tackle')return{executed:true,result:'hold'};return{executed:true,result:'hold'};}
export function processPossession({state,rng,decisions={},emitEvent=null}){if(!state?.ball?.ownerId)return null;const t=num(state.clock?.totalSeconds,state.timeSeconds);if(t<num(state._possessionCooldownUntil,0))return null;const pending=state._pendingAdvantage;if(pending&&t>=pending.expiresAt){const current=state.ball?.ownerId?byId(state,state.ball.ownerId):null;if(!current||sideOf(state,current)!==pending.side||((current.position?.x??pending.x)-pending.x)*(pending.side==='home'?1:-1)<.015){emit(emitEvent,'ADVANTAGE_CANCELLED',{foulType:pending.foulType,side:pending.side,committedById:pending.committedById,sufferedById:pending.sufferedById,position:{x:pending.x,y:pending.y}});state.restart={type:'free_kick',side:pending.side,position:{x:pending.x,y:pending.y},reason:'advantage_cancelled'};state._pendingAdvantage=null;return{executed:true,result:'advantage_cancelled'};}state._pendingAdvantage=null;}const owner=byId(state,state.ball.ownerId);if(!owner||owner.onPitch===false){loose(state);return null;}const side=sideOf(state,owner);const decision=decisions[owner.id]??decisions?.[side]?.[owner.id]??{action:'hold'};const beforeOwner=owner.id,beforeSide=state.possession;state._possessionCooldownUntil=t+.25;const action=String(decision?.action??'hold').toLowerCase();let duel=null;if(['pass','dribble','carry','shoot','cross'].includes(action)){const def=players(state,side==='home'?'away':'home').sort((a,b)=>dist(owner,a)-dist(owner,b))[0];if(def&&dist(owner,def)<.065&&action!=='shoot')duel=resolveDuel({state,attacker:owner,defender:def,rngSource:rng,emitEvent});}
let result;if(duel?.advantage?.played){state._pendingAdvantage={side,expiresAt:t+1.25,x:owner.position.x,y:owner.position.y,foulType:duel.foul?.foulType??'none',committedById:duel.foul?.tacklerId??null,sufferedById:owner.id};} if(duel?.stopped){result={executed:true,result:'foul',duel};}else if(duel?.winner==='defender'&&action!=='shoot'){setPossession(state,side==='home'?'away':'home',duel.defenderId,{silent:true,reason:'duel_win'});result={executed:true,result:'tackled',duel};}else result=execute(state,owner,decision,rng,emitEvent);
emit(emitEvent,'AI_ACTION_RESOLVED',{version:2,playerId:owner.id,decision:action,originalAction:action,action,targetPlayerId:decision?.targetPlayerId??null,decisionScore:num(decision?.score??decision?.decisionScore,null),decisionProbability:decision?.probability??null,execution:!!result?.executed,result:result?.result??'unknown',probability:result?.probability??null,pressureBefore:null,possessionBefore:beforeSide,ownerBefore:beforeOwner,possessionAfter:state.possession,ownerAfter:state.ball?.ownerId??null,duel:duel?{winner:duel.winner,foulType:duel.foul?.foulType??'none',advantagePlayed:!!duel.advantage?.played}:null},owner.id);return result;}
export function getPlayerSide(state,playerId){return sideOf(state,typeof playerId==='object'?playerId:byId(state,playerId));}
export {POSSESSION,ACTIONS};
